[package]
name = "pqbench"
version = "0.1.0"
edition = "2021"

[dependencies]
bsp = { package = "atalanta-bsp", path = "../atalanta-bsp", features = [
    "nest-continue",
    "rt",
] }
fugit = "0.3.7"
ufmt = "0.2.0"
more-asserts = "0.3.1"
rand = { version = "0.9.2", default-features = false, features = ["small_rng"] }
heapless = "0.8.0"
paste = "1.0.15"

[features]
default = ["ufmt"]
ufmt = ["bsp/ufmt", "heapless/ufmt"]
# Use hardware priority queue
use-hwq = []
# Virtualize queue
virtq = []

# Use this feature when using cosimulators such as QuestaSim
rtl-tb = ["bsp/rtl-tb"]
# Use this feature when deploying on FPGA
fpga = ["bsp/fpga"]

[profile.dev]
# There seems to be a problem in riscv-rt with regards to linking in default_start_trap in debug
# mode. `codegen-units = 1` avoids that
codegen-units = 1
opt-level = "s"
