[toolchain]
# The channel definition here is specific to our custom toolchain
channel = "rve"
targets = [
    "riscv32emc-unknown-none-elf", "riscv32em-unknown-none-elf",
    "riscv32imc-unknown-none-elf", "riscv32im-unknown-none-elf"
]
